# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-spring-boot-app
serviceName: accounts-service
appLabel: accounts
appName: accounts

replicaCount: 2

image:
  repository: javaexpress/accounts
  tag: 5.0.0

containerPort: 9095

service:
  type: LoadBalancer
  port: 9898
  targetPort: 8080
